### PR TITLE
Nginx alt

### PR DESCRIPTION
**Pull request by joshuacox**
I was using the `/etc/nginx/templates` folder too much with custom config files.  As there are other autogenerated files in there I do not want to back that folder up directly.  Instead I've been keeping everything specific to containers in /exports. With this branch you can specify the location for an alternate nginx template for a base container with name `basecontainername` who has a `template.ctmpl` in `/exports/basecontianername/` like so:
```
octo config:set basecontainername@/NGINX_ALT '/exports/basecontainername/template.ctmpl'
```

### CODE REVIEW

**Comment by joshuacox** [comment]
Any coments here?  @darron or anyone else,  I'm open to suggestions.  I think it's warranted for the enterprise situation, I need single sign on for a few of my services and that requires altering the nginx configs at the proxy to connect with my FreeIPA setup.  I'm fairly certain there are other scenarios where this would be useful

**Comment by darron** [comment]
Sorry - I had forgotten about this - will take a look this weekend.

**Comment by joshuacox** [comment]
I figured it fell through the cracks.  I'd love feedback as I'm thinking all about my own needs, any ideas on making it more useful or going about it another way are welcome.

**Comment by darron** [comment]
How about something like this?

It's quite a bit cleaner - and I'd like to move all templates out of the nginx folder as well - seems cleaner.

If it's good - I'll adjust the cookbooks to match.

**Comment by joshuacox** [comment]
that looks appropriate to me, I'll test it as soon as I get home this evening.

**Comment by joshuacox** [comment]
verified working on my dev octohost.  All my custom templates were recognized, with no other alterations on my end other than downloading the above octo bin you supplied.  I say merge it, and let's rebuild and test from there

**Comment by darron** [comment]
That should do it now - I've updated the cookbooks and changed the last bit of it in the octo bin.

**Comment by joshuacox** [comment]
looks good to me I'll rebuild tomorrow. Cheers! thanks for implementing!  This completes some major functionality!

**Pull request merged**
